### ISSUE TITLE
Cuda runtime error (device-side assert triggered) during training

### ISSUE THREAD

**Issue by Evelyn910** [brcsomnath/SemAE#1]
According to the instructions provided in README, I tried to train SemAE. 

The environment is exactly same as stated in README, including python and the dependencies.

Unfortunately, there appeared some errors shown as follows:

```
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [27,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCReduceAll.cuh line=327 error=710 : device-side assert triggered

Traceback (most recent call last):
  File "../src/train.py", line 467, in <module>
    model(src, tgt, quantize=quantize, residual_coeff=residual_coeff)
  File "python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "SemAE/src/semae.py", line 161, in forward
    self.encode(src, quantize=quantize, residual_coeff=residual_coeff)
  File "SemAE/src/semae.py", line 110, in encode
    quantize=quantize, residual_coeff=residual_coeff)
  File "python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "SemAE/src/quantizers.py", line 164, in forward
    out = self.encoder(inputs, padding_mask)
  File "python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "SemAE/src/encoders.py", line 71, in forward
    inputs, src_key_padding_mask=padding_mask)
  File "python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "python3.6/site-packages/torch/nn/modules/transformer.py", line 176, in forward
    src_key_padding_mask=src_key_padding_mask)
  File "python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "python3.6/site-packages/torch/nn/modules/transformer.py", line 283, in forward
    key_padding_mask=src_key_padding_mask)[0]
  File "python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "python3.6/site-packages/torch/nn/modules/activation.py", line 783, in forward
    attn_mask=attn_mask)
  File "python3.6/site-packages/torch/nn/functional.py", line 3197, in multi_head_attention_forward
    qkv_same = torch.equal(query, key) and torch.equal(key, value)
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THC/THCReduceAll.cuh:327

Loss: 0.1670876535575965 G Loss: 0.1670876535575965 Q Loss: 0.0:   0%|
```

Would you kindly provide some ideas on how to resolve such issues? I would really appreciate it.

**Comment by brcsomnath** [comment]
Closing this issue after an offline discussion. This issue does not appear while using the correct dependencies as mentioned in the repository.
